/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class startai_com_cn_asjnitest_JniTest */

#ifndef _Included_startai_com_cn_asjnitest_JniTest
#define _Included_startai_com_cn_asjnitest_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     startai_com_cn_asjnitest_JniTest
 * Method:    getMsgFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_startai_com_cn_asjnitest_JniTest_getMsgFromJni
  (JNIEnv *, jobject);

/*
 * Class:     startai_com_cn_asjnitest_JniTest
 * Method:    calculation
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_startai_com_cn_asjnitest_JniTest_calculation
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
